apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: dju-trainee4
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root1234!!
        - name: MYSQL_DATABASE
          value: addressbook
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 150m
            memory: 512Mi
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
